apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    app: devopsaw-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: main
#   # namespace: sample-app-namespace-1773911298403
#   labels:
#     app.kubernetes.io/name: main
#     kubernetes.azure.com/generator: devhub
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: main
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   externalIPs:
#     - 20.99.162.42
