apiVersion: v1
kind: Service
metadata:
  name: devopsaw-app
  # namespace: sample-app-namespace-1773911298403
  # labels:
  #  app.kubernetes.io/name: main
  #  kubernetes.azure.com/generator: devhub
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    
spec:
  type: LoadBalancer
  selector:
    docker.io/rcoope/devopsaw-app:latest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
